export const REVEAL_ORDER = [
  'profession',
  'skill',
  'biological',
  'health',
  'hobby',
  'phobia',
  'baggage',
  'additional_info',
]

export const CATEGORY_LABELS = {
  profession: 'Profession',
  skill: 'Skill',
  biological: 'Biological',
  health: 'Health',
  hobby: 'Hobby',
  phobia: 'Phobia',
  baggage: 'Baggage',
  additional_info: 'Additional Info',
}

export const CATASTROPHES = [
  { name: 'Nuclear War', modifier: 10 },
  { name: 'Zombie Apocalypse', modifier: 6 },
  { name: 'Global Pandemic', modifier: 8 },
  { name: 'AI Takeover', modifier: 4 },
  { name: 'Climate Collapse', modifier: 5 },
  { name: 'Meteor Strike', modifier: 3 },
  { name: 'Alien Invasion', modifier: 9 },
]

export const BUNKERS = [
  { name: 'Fully stocked', modifier: -6 },
  { name: 'Medical facility', modifier: -4 },
  { name: 'Large bunker', modifier: -3 },
  { name: 'High-tech', modifier: -2 },
  { name: 'Limited food', modifier: 4 },
  { name: 'No electricity', modifier: 3 },
  { name: 'Water shortage', modifier: 5 },
  { name: 'Air issues', modifier: 6 },
  { name: 'Small bunker', modifier: 4 },
  { name: 'Damaged bunker', modifier: 6 },
]

export const THRESHOLD_RULES = {
  basePerSurvivor: 9,
  modifierWeight: 0.75,
}

export const CARD_POOLS = {
  profession: [
    { name: 'Emergency Doctor', points: 12 },
    { name: 'Surgeon', points: 12 },
    { name: 'Agricultural Scientist', points: 11 },
    { name: 'Electrical Engineer', points: 10 },
    { name: 'Biologist', points: 10 },
    { name: 'Mechanic', points: 9 },
    { name: 'Civil Engineer', points: 9 },
    { name: 'Farmer', points: 8 },
    { name: 'Survival Instructor', points: 8 },
    { name: 'Nurse', points: 7 },
    { name: 'Firefighter', points: 7 },
    { name: 'Electrician', points: 6 },
    { name: 'Plumber', points: 6 },
    { name: 'Software Developer', points: 5 },
    { name: 'Botanist', points: 5 },
    { name: 'Pharmacist', points: 5 },
    { name: 'Teacher', points: 4 },
    { name: 'Carpenter', points: 4 },
    { name: 'Radio Technician', points: 4 },
    { name: 'Chef', points: 3 },
    { name: 'Nutritionist', points: 3 },
    { name: 'Blacksmith', points: 3 },
    { name: 'Pilot', points: 2 },
    { name: 'Police Officer', points: 2 },
    { name: 'Fitness Trainer', points: 2 },
    { name: 'Historian', points: 1 },
    { name: 'Librarian', points: 1 },
    { name: 'Journalist', points: 1 },
    { name: 'Artist', points: 0 },
    { name: 'Musician', points: 0 },
    { name: 'Actor', points: 0 },
    { name: 'Economist', points: -2 },
    { name: 'Politician', points: -2 },
    { name: 'Lawyer', points: -4 },
    { name: 'Athlete', points: -6 },
    { name: 'Unemployed', points: -8 },
  ],
  skill: [
    { name: 'First Aid Expert', points: 10 },
    { name: 'Water Purification', points: 10 },
    { name: 'Farming Mastery', points: 9 },
    { name: 'Mechanical Repair', points: 8 },
    { name: 'Electrical Systems', points: 7 },
    { name: 'Crisis Management', points: 6 },
    { name: 'Leadership', points: 5 },
    { name: 'Engineering Design', points: 4 },
    { name: 'Cooking (Survival)', points: 3 },
    { name: 'Negotiation', points: 2 },
    { name: 'Improvisation', points: 2 },
    { name: 'Brewing Alcohol', points: 1 },
  ],
  biological: [
    { name: 'Genius IQ', points: 8 },
    { name: 'Excellent Immune System', points: 7 },
    { name: 'Athletic', points: 6 },
    { name: 'High Stamina', points: 6 },
    { name: 'Strong', points: 5 },
    { name: 'Fast Reflexes', points: 5 },
    { name: 'Fertile', points: 4 },
    { name: 'High Pain Tolerance', points: 3 },
    { name: 'Charismatic', points: 2 },
    { name: 'Average', points: 1 },
    { name: 'Neutral Traits', points: 0 },
    { name: 'Poor Eyesight', points: -2 },
    { name: 'Socially Awkward', points: -3 },
    { name: 'Weak', points: -4 },
    { name: 'Obese', points: -5 },
    { name: 'Infertile', points: -6 },
  ],
  health: [
    { name: 'Perfect Health', points: 6 },
    { name: 'Strong Immune System', points: 5 },
    { name: 'Minor Allergies', points: 3 },
    { name: 'Stable', points: 0 },
    { name: 'Anxiety', points: -3 },
    { name: 'Insomnia', points: -3 },
    { name: 'Chronic Pain', points: -5 },
    { name: 'Diabetes', points: -7 },
    { name: 'PTSD', points: -9 },
    { name: 'Heart Condition', points: -9 },
    { name: 'Epilepsy', points: -10 },
    { name: 'Cancer (early)', points: -11 },
    { name: 'Terminal Illness', points: -12 },
    { name: 'Paralysis', points: -12 },
  ],
  hobby: [
    { name: 'Gardening', points: 4 },
    { name: 'Hunting', points: 4 },
    { name: 'Electronics Repair', points: 4 },
    { name: 'Cooking', points: 3 },
    { name: 'Crafting', points: 3 },
    { name: 'Hiking', points: 2 },
    { name: 'Chess', points: 2 },
    { name: 'Fitness Activities', points: 1 },
    { name: 'Gaming', points: 0 },
    { name: 'Blogging', points: 0 },
    { name: 'Entertainment', points: 0 },
  ],
  phobia: [
    { name: 'Claustrophobia', points: -8 },
    { name: 'Disease Phobia', points: -8 },
    { name: 'Darkness', points: -7 },
    { name: 'Fire', points: -7 },
    { name: 'Water', points: -6 },
    { name: 'Animals', points: -6 },
    { name: 'Conflict', points: -5 },
    { name: 'Crowds', points: -3 },
    { name: 'Minor fears', points: -1 },
    { name: 'No Phobia', points: 0 },
  ],
  baggage: [
    { name: 'Portable water purifier', points: 6 },
    { name: 'Trauma medical bag', points: 5 },
    { name: 'Seed vault canister', points: 4 },
    { name: 'Heavy-duty tool kit', points: 4 },
    { name: 'Solar charger', points: 3 },
    { name: 'Rope and climbing gear', points: 3 },
    { name: 'Camping stove', points: 2 },
    { name: 'Flashlight set', points: 2 },
    { name: 'Warm blankets', points: 1 },
    { name: 'Spare batteries', points: 1 },
    { name: 'Family photo album', points: 0 },
    { name: 'Deck of cards', points: 0 },
    { name: 'Heavy luxury suitcase', points: -2 },
    { name: 'Broken gaming console', points: -3 },
    { name: 'Crate of useless collectibles', points: -4 },
    { name: 'Leaking fuel canister', points: -5 },
    { name: 'Biohazard sample case', points: -6 },
  ],
  additional_info: [
    { name: 'Immune to catastrophe', points: 8 },
    { name: 'Critical resources', points: 7 },
    { name: 'Knows safe zone', points: 6 },
    { name: 'Food supply', points: 5 },
    { name: 'Strategic knowledge', points: 4 },
    { name: 'Persuasive', points: 3 },
    { name: 'Planner', points: 2 },
    { name: 'Neutral', points: 1 },
    { name: 'No effect', points: 0 },
    { name: 'Annoying', points: -2 },
    { name: 'Manipulated', points: -3 },
    { name: 'Risky', points: -4 },
    { name: 'Conflict source', points: -6 },
    { name: 'Disease carrier', points: -7 },
    { name: 'Will betray', points: -8 },
  ],
}
