# Generated by Django 6.0.3 on 2026-03-28 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bunker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('modifier', models.IntegerField()),
                ('is_positive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('points', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['card_type', '-points'],
            },
        ),
        migrations.CreateModel(
            name='CardType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_type', models.CharField(choices=[('profession', 'Profession'), ('skill', 'Skill'), ('biological', 'Biological'), ('health', 'Health'), ('hobby', 'Hobby'), ('phobia', 'Phobia'), ('baggage', 'Baggage'), ('additional_info', 'Additional Info')], max_length=20, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Catastrophe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('modifier', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='GameLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('phase_change', 'Phase Changed'), ('card_revealed', 'Card Revealed'), ('player_eliminated', 'Player Eliminated'), ('voting_round', 'Voting Round'), ('game_ended', 'Game Ended')], max_length=50)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_id', models.CharField(max_length=50, unique=True)),
                ('current_phase', models.CharField(choices=[('setup', 'Setup'), ('reveal', 'Reveal Rounds'), ('voting', 'Voting'), ('final_scoring', 'Final Scoring'), ('completed', 'Completed')], default='setup', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('failed', 'Failed')], default='active', max_length=20)),
                ('base_threshold', models.IntegerField(default=0)),
                ('final_threshold', models.IntegerField(default=0)),
                ('final_score', models.IntegerField(blank=True, null=True)),
                ('max_players', models.IntegerField(default=8)),
                ('survivors_needed', models.IntegerField(default=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bunker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bunker')),
                ('catastrophe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.catastrophe')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_games', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profession_revealed', models.BooleanField(default=False)),
                ('skill_revealed', models.BooleanField(default=False)),
                ('biological_revealed', models.BooleanField(default=False)),
                ('health_revealed', models.BooleanField(default=False)),
                ('hobby_revealed', models.BooleanField(default=False)),
                ('phobia_revealed', models.BooleanField(default=False)),
                ('baggage_revealed', models.BooleanField(default=False)),
                ('additional_info_revealed', models.BooleanField(default=False)),
                ('is_eliminated', models.BooleanField(default=False)),
                ('eliminated_round', models.IntegerField(blank=True, null=True)),
                ('total_score', models.IntegerField(default=0)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSpecialCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SpecialCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('effect', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='VoteRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('game_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vote_rounds', to='core.gamesession')),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.AddField(
            model_name='card',
            name='card_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cardtype'),
        ),
        migrations.AddField(
            model_name='gamelog',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='core.gamesession'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='additional_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='additional_info_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='baggage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baggage_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='biological',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='biological_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='game_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='core.gamesession'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='health',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='health_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='hobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hobby_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='phobia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='phobia_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='player',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='profession',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profession_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerhand',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='skill_players', to='core.card'),
        ),
        migrations.AddField(
            model_name='playerspecialcard',
            name='player_hand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='special_cards', to='core.playerhand'),
        ),
        migrations.AddField(
            model_name='playerspecialcard',
            name='special_condition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.specialcondition'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voted_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='core.playerhand'),
        ),
        migrations.AddField(
            model_name='vote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_cast', to='core.playerhand'),
        ),
        migrations.AddField(
            model_name='vote',
            name='vote_round',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.voteround'),
        ),
    ]
