# Generated by Django 6.0.3 on 2026-03-28 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bunker_card_cardtype_catastrophe_gamelog_gamesession_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='ending_narration',
            field=models.TextField(blank=True, help_text='Reflective ending narration text read at game conclusion'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='narration_audio_url',
            field=models.URLField(blank=True, help_text='URL to generated opening narration audio file'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='opening_narration',
            field=models.TextField(blank=True, help_text='Dramatic opening narration text read at game start'),
        ),
    ]
