export const REVEAL_ORDER = [
  'profession',
  'skill',
  'age',
  'health',
  'hobby',
  'phobia',
  'baggage',
  'additional_info',
]

export const CATEGORY_LABELS = {
  profession: 'Profession',
  skill: 'Skill',
  age: 'Age',
  health: 'Health',
  hobby: 'Hobby',
  phobia: 'Phobia',
  baggage: 'Baggage',
  additional_info: 'Additional Info',
}

export const CATASTROPHES = [
  { name: 'Nuclear War', modifier: 10 },
  { name: 'Zombie Apocalypse', modifier: 6 },
  { name: 'Global Pandemic', modifier: 8 },
  { name: 'AI Takeover', modifier: 4 },
  { name: 'Climate Collapse', modifier: 5 },
  { name: 'Meteor Strike', modifier: 3 },
  { name: 'Alien Invasion', modifier: 9 },
]

export const BUNKERS = [
  { name: 'Fully stocked bunker', modifier: -6 },
  { name: 'Limited food', modifier: 4 },
  { name: 'Advanced medical facility', modifier: -4 },
  { name: 'No electricity', modifier: 3 },
  { name: 'Small bunker', modifier: 4 },
  { name: 'Large bunker', modifier: -3 },
  { name: 'Water shortage', modifier: 5 },
  { name: 'Air filtration issues', modifier: 6 },
  { name: 'High-tech bunker', modifier: -2 },
  { name: 'Damaged bunker', modifier: 6 },
]

export const THRESHOLD_RULES = {
  basePerSurvivor: 9,
  modifierWeight: 0.75,
}

export const CARD_POOLS = {
  profession: [
    { name: 'Emergency Doctor', points: 12 },
    { name: 'Surgeon', points: 12 },
    { name: 'Nurse', points: 7 },
    { name: 'Psychologist', points: 3 },
    { name: 'Veterinarian', points: 5 },
    { name: 'Farmer', points: 8 },
    { name: 'Agricultural Scientist', points: 11 },
    { name: 'Electrical Engineer', points: 10 },
    { name: 'Mechanic', points: 9 },
    { name: 'Civil Engineer', points: 9 },
    { name: 'Software Developer', points: 5 },
    { name: 'Cybersecurity Specialist', points: 4 },
    { name: 'Teacher', points: 4 },
    { name: 'Survival Instructor', points: 8 },
    { name: 'Soldier', points: 2 },
    { name: 'Firefighter', points: 3 },
    { name: 'Police Officer', points: 2 },
    { name: 'Pilot', points: 2 },
    { name: 'Chef', points: 3 },
    { name: 'Nutritionist', points: 3 },
    { name: 'Biologist', points: 10 },
    { name: 'Chemist', points: 7 },
    { name: 'Physicist', points: 6 },
    { name: 'Botanist', points: 5 },
    { name: 'Geologist', points: 5 },
    { name: 'Architect', points: 6 },
    { name: 'Plumber', points: 6 },
    { name: 'Carpenter', points: 4 },
    { name: 'Electrician', points: 6 },
    { name: 'Blacksmith', points: 3 },
    { name: 'Tailor', points: 2 },
    { name: 'Pharmacist', points: 5 },
    { name: 'Dentist', points: 4 },
    { name: 'Journalist', points: 1 },
    { name: 'Politician', points: -2 },
    { name: 'Economist', points: -2 },
    { name: 'Lawyer', points: -4 },
    { name: 'Artist', points: 0 },
    { name: 'Musician', points: 0 },
    { name: 'Actor', points: 0 },
    { name: 'Athlete', points: -6 },
    { name: 'Fitness Trainer', points: 2 },
    { name: 'Archaeologist', points: 3 },
    { name: 'Historian', points: 1 },
    { name: 'Librarian', points: 1 },
    { name: 'Game Developer', points: -2 },
    { name: 'Drone Operator', points: -5 },
    { name: 'Radio Technician', points: 4 },
    { name: 'Truck Driver', points: 2 },
    { name: 'Unemployed', points: -8 },
  ],
  skill: [
    { name: 'First Aid Expert', points: 10 },
    { name: 'Expert negotiator', points: 2 },
    { name: 'Fire starting (no tools)', points: 6 },
    { name: 'Expert hunter', points: 8 },
    { name: 'Fishing mastery', points: 7 },
    { name: 'Farming (high yield crops)', points: 9 },
    { name: 'Animal taming', points: 5 },
    { name: 'Mechanical repair', points: 8 },
    { name: 'Electrical wiring', points: 7 },
    { name: 'Coding & automation', points: 5 },
    { name: 'Weapon handling', points: 6 },
    { name: 'Tracking & scouting', points: 6 },
    { name: 'Map navigation', points: 5 },
    { name: 'Leadership', points: 5 },
    { name: 'Team motivation', points: 4 },
    { name: 'Cooking (limited supplies)', points: 3 },
    { name: 'Herbal medicine', points: 6 },
    { name: 'Poison identification', points: 5 },
    { name: 'Lock picking', points: 4 },
    { name: 'Stealth movement', points: 4 },
    { name: 'Public speaking', points: 2 },
    { name: 'Fast learner', points: 4 },
    { name: 'Multilingual', points: 2 },
    { name: 'Improvisation', points: 3 },
    { name: 'Crisis management', points: 6 },
    { name: 'Engineering design', points: 4 },
    { name: 'Construction planning', points: 5 },
    { name: 'Water purification', points: 10 },
    { name: 'Brewing Alcohol', points: 1 },
    { name: 'Teaching others', points: 3 },
  ],
  age: [
    { name: '16', points: -2 },
    { name: '18', points: 1 },
    { name: '20', points: 2 },
    { name: '22', points: 3 },
    { name: '24', points: 3 },
    { name: '26', points: 3 },
    { name: '28', points: 3 },
    { name: '30', points: 2 },
    { name: '32', points: 2 },
    { name: '34', points: 2 },
    { name: '36', points: 2 },
    { name: '38', points: 2 },
    { name: '40', points: 2 },
    { name: '42', points: 1 },
    { name: '44', points: 1 },
    { name: '46', points: 1 },
    { name: '48', points: 1 },
    { name: '50', points: 0 },
    { name: '52', points: 0 },
    { name: '54', points: 0 },
    { name: '56', points: -1 },
    { name: '58', points: -1 },
    { name: '60', points: -2 },
    { name: '62', points: -2 },
    { name: '64', points: -3 },
    { name: '66', points: -3 },
    { name: '68', points: -4 },
    { name: '70', points: -4 },
    { name: '72', points: -5 },
    { name: '75', points: -6 },
  ],
  health: [
    { name: 'Perfect Health', points: 6 },
    { name: 'Minor allergies', points: 3 },
    { name: 'Asthma', points: -2 },
    { name: 'Diabetes', points: -7 },
    { name: 'Heart condition', points: -9 },
    { name: 'Cancer (early stage)', points: -11 },
    { name: 'Cancer (terminal)', points: -12 },
    { name: 'Broken leg (healing)', points: -4 },
    { name: 'Blind in one eye', points: -3 },
    { name: 'Deaf in one ear', points: -2 },
    { name: 'Chronic migraines', points: -3 },
    { name: 'PTSD', points: -9 },
    { name: 'Anxiety disorder', points: -3 },
    { name: 'Depression', points: -3 },
    { name: 'Addicted to nicotine', points: -4 },
    { name: 'Addicted to alcohol', points: -5 },
    { name: 'Strong Immune System', points: 5 },
    { name: 'Weak immune system', points: -5 },
    { name: 'Insomnia', points: -3 },
    { name: 'Sleep apnea', points: -3 },
    { name: 'Paralysis (partial)', points: -12 },
    { name: 'Fully healthy athlete', points: 6 },
    { name: 'Recovering from surgery', points: -2 },
    { name: 'Epilepsy', points: -10 },
    { name: 'Severe allergies (food)', points: -4 },
    { name: 'Color blindness', points: -1 },
    { name: 'Chronic Pain', points: -5 },
    { name: 'ADHD', points: -2 },
    { name: 'Bipolar disorder', points: -4 },
    { name: 'No medical issues', points: 0 },
  ],
  hobby: [
    { name: 'Gardening', points: 4 },
    { name: 'Hunting', points: 4 },
    { name: 'Fishing', points: 4 },
    { name: 'Painting', points: 0 },
    { name: 'Playing guitar', points: 0 },
    { name: 'Writing stories', points: 0 },
    { name: 'Gaming', points: -1 },
    { name: 'Cooking', points: 3 },
    { name: 'Baking', points: 2 },
    { name: 'Hiking', points: 2 },
    { name: 'Camping', points: 2 },
    { name: 'Martial arts', points: 2 },
    { name: 'Wood carving', points: 3 },
    { name: 'Metalworking', points: 3 },
    { name: 'Sewing', points: 2 },
    { name: 'Photography', points: 0 },
    { name: 'Blogging', points: -2 },
    { name: 'Collecting items', points: 0 },
    { name: 'Astronomy', points: 1 },
    { name: 'Bird watching', points: 0 },
    { name: 'Brewing drinks', points: 1 },
    { name: 'Dancing', points: 0 },
    { name: 'Acting', points: 0 },
    { name: 'Magic tricks', points: 0 },
    { name: 'Chess', points: 2 },
    { name: 'Board games', points: 0 },
    { name: 'DIY crafting', points: 2 },
    { name: 'Repairing electronics', points: 4 },
    { name: 'Swimming', points: 2 },
    { name: 'Running', points: 1 },
  ],
  phobia: [
    { name: 'Fear of darkness', points: -7 },
    { name: 'Fear of heights', points: -4 },
    { name: 'Fear of water', points: -6 },
    { name: 'Fear of fire', points: -7 },
    { name: 'Fear of blood', points: -4 },
    { name: 'Fear of animals', points: -6 },
    { name: 'Fear of insects', points: -3 },
    { name: 'Fear of enclosed spaces', points: -12 },
    { name: 'Fear of open spaces', points: -5 },
    { name: 'Fear of loud noises', points: -3 },
    { name: 'Fear of disease', points: -8 },
    { name: 'Fear of death', points: -4 },
    { name: 'Fear of strangers', points: -2 },
    { name: 'Fear of isolation', points: -4 },
    { name: 'Fear of leadership', points: -5 },
    { name: 'Fear of conflict', points: -5 },
    { name: 'Fear of responsibility', points: -5 },
    { name: 'Fear of weapons', points: -4 },
    { name: 'Fear of failure', points: -3 },
    { name: 'Fear of pain', points: -4 },
    { name: 'Fear of storms', points: -3 },
    { name: 'Fear of cold', points: -2 },
    { name: 'Fear of heat', points: -2 },
    { name: 'Fear of technology', points: -3 },
    { name: 'Fear of authority', points: -2 },
    { name: 'Fear of crowds', points: -3 },
    { name: 'Fear of silence', points: -1 },
    { name: 'Fear of the unknown', points: -3 },
    { name: 'Fear of abandonment', points: -4 },
    { name: 'No phobias', points: 0 },
  ],
  baggage: [
    { name: 'Backpack of canned food', points: 5 },
    { name: 'Water purification kit', points: 7 },
    { name: 'Medical supply kit', points: 7 },
    { name: 'Handgun (limited ammo)', points: 3 },
    { name: 'Rifle (limited ammo)', points: 4 },
    { name: 'Toolbox (basic tools)', points: 6 },
    { name: 'Advanced toolkit (mechanical/electrical)', points: 7 },
    { name: 'Seeds (variety crops)', points: 6 },
    { name: 'Portable solar panel', points: 6 },
    { name: 'Battery pack (high capacity)', points: 5 },
    { name: 'Gas mask (high quality)', points: 5 },
    { name: 'Radiation suit (damaged)', points: 2 },
    { name: 'Radiation suit (intact)', points: 6 },
    { name: 'Map of surrounding area', points: 4 },
    { name: 'Compass & navigation tools', points: 3 },
    { name: 'Fishing kit', points: 4 },
    { name: 'Hunting traps', points: 4 },
    { name: 'Cooking equipment', points: 3 },
    { name: 'Knife (durable)', points: 3 },
    { name: 'Multi-tool', points: 5 },
    { name: 'Rope (50m, durable)', points: 2 },
    { name: 'Flashlight (low battery)', points: 1 },
    { name: 'Flashlight (high battery)', points: 3 },
    { name: 'Portable radio', points: 4 },
    { name: 'Satellite phone (limited charge)', points: 5 },
    { name: 'Fuel canister', points: 3 },
    { name: 'Vehicle (damaged, repairable)', points: 2 },
    { name: 'Vehicle (fully functional)', points: 6 },
    { name: 'Book: survival manual', points: 3 },
  ],
  additional_info: [
    { name: 'Can have children', points: 2 },
    { name: 'Cannot have children', points: -2 },
    { name: 'Knows location of safe zone', points: 6 },
    { name: 'Has hidden weapon', points: 3 },
    { name: 'Has extra food supply', points: 5 },
    { name: 'Has medicine stash', points: 7 },
    { name: 'Knows secret bunker flaw', points: 4 },
    { name: 'Immune to disease', points: 8 },
    { name: 'Carrier of disease', points: -7 },
    { name: 'Has survival guide book', points: 3 },
    { name: 'Has pet companion', points: -1 },
    { name: 'Has valuable tools', points: 7 },
    { name: 'Has communication device', points: 4 },
    { name: 'Knows farming secrets', points: 6 },
    { name: 'Knows engineering blueprints', points: 6 },
    { name: 'Has map of area', points: 4 },
    { name: 'Has hidden agenda', points: -3 },
    { name: 'Trusted by group', points: 4 },
    { name: 'Hated by group', points: -4 },
    { name: 'Has leadership claim', points: 3 },
    { name: 'Quiet observer', points: 1 },
    { name: 'Talks too much', points: -2 },
    { name: 'Highly persuasive', points: 3 },
    { name: 'Easily manipulated', points: -3 },
    { name: 'Risk taker', points: -4 },
    { name: 'Very cautious', points: 2 },
    { name: 'Strong moral code', points: 3 },
    { name: 'Will betray if needed', points: -8 },
    { name: 'Secret hero', points: 6 },
    { name: 'Secret villain', points: -7 },
  ],
}
